pipeline:
  deploy:
    name: upload
    image: gcr.io/dd-operations-dev/cloudcli
    commands:
      - bash -c 'gcloud auth activate-service-account $GC_ACCOUNT --key-file=$GOOGLE_APPLICATION_CREDENTIALS'
      - bash -c 'mkdir dags && cd dags'
      - bash -c 'curl -H "Authorization:token $GITHUB_TOKEN" -L https://codeload.github.com/BeenVerifiedInc/data-eng-airflow/tar.gz/master > repo_dags.gz | tar -xz --strip=2 data-eng-airflow-master/dags'
      - bash -c 'gsutil cp -r . gs://dd-operations-dev/us-east1-oil-refinery-841c5de2-bucket/dags'
      - bash -c 'cd .. && rm -r dags'
    volumes:
      - /Users/nroman/dagkey.json:/tmp/secrets/google/key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/secrets/google/key.json
      - GC_ACCOUNT=airflow-dag-deployments@dd-operations-dev.iam.gserviceaccount.com
    secrets:
      - github_token
    when:
      branch: master
