pipeline:
  deploy:
    name: upload
    image: gcr.io/dd-operations-dev/cloudcli:2e4d7e
    commands:
        - bash -c 'gsutil cp -r ./dags/ gs://dd-operations-dev/us-east1-oil-refinery-841c5de2-bucket/dags'
    volumes:
        - /Users/nroman/dagskey.json:/tmp/secrets/google/key.json
    environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/tmp/secrets/google/key.json
        - GC_ACCOUNT=airflow-dag-deployments@dd-operations-dev.iam.gserviceaccount.com

