pipeline:
  deploy:
    name: upload
    image: gcr.io/dd-operations-dev/cloudcli
    commands:
        - gsutil cp -r ./test/ gs://dd-operations-dev/us-east1-oil-refinery-841c5de2-bucket/dags
    volumes:
        - /Users/nroman/dd-operations-dev-airflow-dag-deployments-key.json:/tmp/secrets/google/key.json
    environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/tmp/secrets/google/key.json
    secrets: 
        - gc_account
    when:
        branch: master
