pipeline:
  deploy:
    name: upload
    image: plugins/gcs
    source: ./test/
    target: us-east1-oil-refinery-841c5de2-bucket/dags
    ignore: bin/*
    cache_control: private,max-age=90
    token:
      from_secret: google_application_credentials
    when:
      branch: master
