pipeline:
  deploy:
    name: upload
    image: gcr.io/dd-operations-dev/de-cmd-gittogcs
    volumes:
      - /Users/nroman/dagkey.json:/tmp/secrets/google/key.json
    environment:
      - GITHUB_USER=BeenVerifiedInc
      - GITHUB_REPO=data-eng-airflow
      - BRANCH=master
      - DIR=dags
      - GCS_PATH=gs://dd-operations-dev/us-east1-oil-refinery-841c5de2-bucket/dags
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/secrets/google/key.json
      - GC_ACCOUNT=airflow-dag-deployments@dd-operations-dev.iam.gserviceaccount.com
    secrets:
      - github_token
    when:
      branch: master
