pipeline:
  deploy:
    name: upload
    image: gcr.io/dd-operations-dev/cloudcli
    commands:
      - gsutil cp -r ./test/ gs://dd-operations-dev/us-east1-oil-refinery-841c5de2-bucket/dags
    secrets: 
      - google_application_credentials
      - gc_account
    when:
      branch: master
