pipeline:
  gcs:
    image: wyattjoh/drone-gcs
    acl: private
    bucket: "dd-operations-dev"
    source: ./dags/
    target: us-east1-oil-refinery-841c5de2-bucket/dags
    secrets: google_application_credentials
  when:
    branch: master
